Write a Python program to convert an array to an ordinary list with the same items.

In [1]:
from array import *
def array_list(array_num):
    num_list = array_num.tolist() # list
    print(num_list)
  
# driver code
array_num = array('i', [45,34,67]) # array
array_list(array_num)

[45, 34, 67]


Write a NumPy program to compute the sum of the diagonal elements of a given array.


In [3]:
import numpy as np
m = np.arange(6).reshape(3,2)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1]
 [2 3]
 [4 5]]
Condition number of the said matrix:
3


Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 : then 3 and 5 are higher than 2.

In [4]:
def choice_array(array_num,x):
  return array_num[array_num>x]
      

array_num= np.array([[1,2],[3,5]])

print(choice_array(array_num,2))

[3 5]


Given two arrays, A & B have the same shape.

The task is to apply addition by hand: C is the new array.

In [5]:
def addition(a,b):
  c=a+b
  return c

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2],[3,4],[5,6]])
print(addition(a,b))

[[ 2  4]
 [ 6  8]
 [10 12]]


Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [6]:
import numpy as np
from numpy.core.fromnumeric import mean
def program(m):
  #m=np.array(m)
  #r=mean(m[:])
  return m-m.mean(axis=1,keepdims=True)# row is 1,column is 0

y=np.arange(6).reshape(3,2)
print(y)
print(program(y))

[[0 1]
 [2 3]
 [4 5]]
[[-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]]
